### ISSUE TITLE
Can both qt5 and qt6 be used?

### ISSUE THREAD

**Issue by tio-trom** [trialuser02/qt5gtk2#1]
If one adds:
```
export QT_QPA_PLATFORMTHEME=qt5gtk2
export QT_QPA_PLATFORMTHEME=qt6gtk2
```
Would that be the way to cover both qt5 and qt6 considering both qt5gtk2 and qt6gtk2 are installed on the system?

**Comment by trialuser02** [comment]
After recent changes both variants should work,
